fix: CVE-2026-42945
Ref: https://www.cve.org/CVERecord?id=CVE-2026-42945

diff --git a/git-backend/Dockerfile b/git-backend/Dockerfile
--- a/git-backend/Dockerfile
+++ b/git-backend/Dockerfile
@@ -15,6 +15,22 @@ ARG USE_SJTUG
 RUN if [ "$USE_SJTUG" = true ] ; then sed -i 's/http:\/\/deb.debian.org/http:\/\/mirrors.ustc.edu.cn/g' /etc/apt/sources.list.d/debian.sources ; fi
 RUN if [ "$USE_SJTUG" = true ] ; then sed -i 's/http:\/\/security.debian.org/http:\/\/mirrors.ustc.edu.cn/g' /etc/apt/sources.list.d/debian.sources ; fi
 
+# Install latest Nginx
+# Ref: https://nginx.org/en/linux_packages.html#Debian
+RUN apt-get update \
+    && apt install -yy curl gnupg2 ca-certificates lsb-release debian-archive-keyring
+RUN curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor \
+    | tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null
+RUN mkdir -p ~/.gnupg && chmod 0700 ~/.gnupg
+RUN gpg --dry-run --quiet --no-keyring --import --import-options import-show /usr/share/keyrings/nginx-archive-keyring.gpg \
+    | grep '573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62' \
+    || { echo "ERROR: nginx key fingerprint mismatch"; exit 1; }
+RUN echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] \
+https://nginx.org/packages/debian $(lsb_release -cs) nginx" \
+    | tee /etc/apt/sources.list.d/nginx.list
+RUN echo -e "Package: *\nPin: origin nginx.org\nPin: release o=nginx\nPin-Priority: 900\n" \
+    | tee /etc/apt/preferences.d/99nginx
+
 # We need the following:
 # - git, because that gets us the git-http-backend CGI script
 # - fcgiwrap, because that is how nginx does CGI
